# Generated by Django 5.2.8 on 2025-11-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Car',
        ),
    ]
